#! /usr/bin/python3
import pygame
pygame.init()
ekraan = pygame.display.set_mode((400, 400))
kell = pygame.time.Clock()
pygame.mixer.music.load("/usr/share/hunt-ja-janes/kullmuusika.mp3")
pygame.mixer.music.play(-1)
janku_pilt = pygame.image.load("/usr/share/hunt-ja-janes/janku.png")
hundi_pilt = pygame.image.load("/usr/share/hunt-ja-janes/hunt.png")
logo = pygame.image.load("/usr/share/hunt-ja-janes/logo_must_kiri.png")
janku_rect = janku_pilt.get_rect()
font = pygame.font.Font(None, 25)

# algus- ja sihtpunkt
hunt = pygame.math.Vector2(0, 0)
janku_rect.x, janku_rect.y = [300,300]

kiirus = 2
suund = "vasakule"
running = True
aeg = 0
kaader = 0
algus = True
while algus:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
            exit()
        elif e.type == pygame.KEYDOWN:
            algus = False
    ekraan.fill((0,255,0))
    ekraan.blit(logo, [0,0])
    ekraan.blit(font.render("Hunt ja jänku", 1, "black"), [0,50])
    ekraan.blit(font.render("Põgene hundi eest!", 1, "black"), [0,75])
    ekraan.blit(font.render("Nooleklahvidega liigub", 1, "black"), [0,100])
    ekraan.blit(font.render("Veebileht: valeNimi4.github.io/huntjajanes", 1, "black"), [0,125])
    ekraan.blit(font.render("Vajuta alustamiseks suvalist klahvi", 1, "black"), [0,150])
    ekraan.blit(font.render("(c) valeNimi4", 1, "black"), [0, 175])
    ekraan.blit(font.render("Litsents: GPL v3", 1, "black"), [0,200])
    pygame.display.flip()
m2ng = True
while m2ng:
    kaader += 1
    if kaader == 60:
        kaader = 1
        aeg += 1
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
            exit()
        elif e.type == pygame.KEYDOWN:
            if e.key == pygame.K_RIGHT:
                suund = "paremale"
            elif e.key == pygame.K_LEFT:
                suund = "vasakule"
            elif e.key == pygame.K_DOWN:
                suund = "alla"
            elif e.key == pygame.K_UP:
                suund = "üles"
    if suund == "paremale":
        janku_rect.x += 3
    elif suund == "vasakule":
        janku_rect.x -= 3
    elif suund == "alla":
        janku_rect.y += 3
    elif suund == "üles":
        janku_rect.y -= 3
    if janku_rect.x > 397:
        janku_rect.x = 394
    elif janku_rect.x < 0:
        janku_rect.x = 0
    if janku_rect.y > 400:
        janku_rect.y = 397
    elif janku_rect.y < 0:
        janku_rect.y = 0
    janku = pygame.math.Vector2(janku_rect.x, janku_rect.y)
    # liikumine vektoriga
    kurss = janku - hunt
    kurss = kurss.normalize() * kiirus
    hunt += kurss
    if janku_rect.colliderect(pygame.Rect(int(hunt.x), int(hunt.y), 50, 25)):
        m2ng = False
    ekraan.fill((0, 255, 0))
    ekraan.blit(hundi_pilt, [int(hunt.x), int(hunt.y)])
    ekraan.blit(janku_pilt, janku_rect)
    ekraan.blit(font.render(str(aeg), 1, "black"), [0,0])
    pygame.display.flip()
    kell.tick(60)
while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
            exit()
        elif e.type == pygame.KEYDOWN:
            algus = False
    ekraan.fill((0,255,0))
    ekraan.blit(logo, [0,0])
    ekraan.blit(font.render("Mäng läbi!", 1, "black"), [0,50])
    ekraan.blit(font.render("Sinu aeg: "+str(aeg), 1, "black"), [0,75])
    ekraan.blit(font.render("Aitäh, et mängisite", 1, "black"), [0,100])
    ekraan.blit(font.render("(c) valeNimi4", 1, "black"), [0, 125])
    ekraan.blit(font.render("Litsents: GPL v3", 1, "black"), [0,150])
    pygame.display.flip()
